### PR TITLE
CS Fixes

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by pda** [comment]
Looking good, apart from the failing tests.
Is this mostly the result of http://cs.sensiolabs.org/ / https://github.com/FriendsOfPHP/PHP-CS-Fixer with a few manual changes like `in_array()` added?

**Comment by GrahamCampbell** [comment]
I actually ran this through https://styleci.io/, and yeh, I made a few manual changes too.

**Comment by GrahamCampbell** [comment]
> Looking good, apart from the failing tests.

Yeh, I missed a closing bracket when i did the in_array thing. Oops.

**Comment by GrahamCampbell** [comment]
I'd recommend you enabled StyleCI on this repo actually. It'll review all your comments and PRs for you.

**Comment by GrahamCampbell** [comment]
I used this config:

```yaml
preset: recommended

linting: true

enabled:
  - long_array_syntax

disabled:
  - short_array_syntax
  - phpdoc_no_package
```

**Comment by GrahamCampbell** [comment]
Tests are passing now btw. :)

**Comment by pda** [comment]
Nice. I've enabled StyleCI. Should that config be committed as part of this PR, then?

**Comment by GrahamCampbell** [comment]
> Should that config be committed as .styleci.yml in this PR, then?

No. You can just use the in-browser config. I mentioned it in a blog post: https://blog.alt-three.com/the-next-generation-of-styleci/.

**Comment by pda** [comment]
Cool, thanks. I also disabled `phpdoc_separation` since it wanted to add lots of blank docblock lines to this PR branch.

I guess it might make sense to switch to the committed `.styleci.yml` style once master becomes a v4.0 candidate and PHP 5.3 syntax limitations are dropped.

**Comment by GrahamCampbell** [comment]
> I guess it might make sense to switch to the committed .styleci.yml style once master becomes a v4.0 candidate and PHP 5.3 syntax limitations are dropped.

Sure.

> Cool, thanks. I also disabled phpdoc_separation since it wanted to add lots of blank docblock lines to this PR branch.

Oh, yeh, forgot about that. It was useful to fix the return/param spacing, but I forgot, i had to revert the other spacing changes it made.

**Pull request merged**
