### PR TITLE
Fix : infinite loop in case of remote beanstalk server goes unreachable network

### PR DESCRIPTION
**Pull request by matang-dave**
Fixed :
In case of the remote beanstalk server goes unreachable , getLine() function goes into an infinite loop .
Now, added an extra check that , if there is any error , check if the timeout is there , and if so, try to re-connect to the server .

### CODE REVIEW

**Comment by airoude** [comment]
Ping @matang-dave could you please fix the CS?

**Comment by matang-dave** [comment]
@airoude  , did not understand acronym CS . Can you please explain .

**Comment by airoude** [comment]
@matang-dave it stands for Code Style :) The StyleCI fails because of [this indent](https://github.com/pda/pheanstalk/pull/137/files#diff-694b0af5cdeca6b630ea2e97bc012b18R107).

**Comment by SamMousa** [comment]
Closing this in favor of #163

**Pull request closed without merging**
