### PR TITLE
Updated phpunit, implemented #117, #118.

### PR DESCRIPTION
**Pull request by SamMousa**
This PR implements #117 and #118.
It also updated phpunit and added a method for easily running tests via docker-compose.

### CODE REVIEW

**Comment by SamMousa** [comment]
@DavidGoodwin your feedback is appreciated, if you have any :)

**Comment by SamMousa** [comment]
Hmm, guess that makes sense; even if it's only for the edge case where a developer doesn't have it installed.

Thanks, will add it and merge today / tomorrow!

**Comment by DavidGoodwin** [comment]
for composer.json -> the php version requirement is not the same between require and require-dev; is that intentional?

**Comment by SamMousa** [comment]
Uhm, require-dev is phpunit version not PHP ;-)

**Pull request merged**
